### ISSUE TITLE
Error: Failed to link vertex and fragment shaders.

### ISSUE THREAD

**Issue by allrightzhu** [cloud-annotations/classification-react#1]
when I try to run the model I trained from the Cloud Annotations,the React App web had an error in the page like this,    Error: Failed to link vertex and fragment shaders.

**Comment by bourdakos1** [comment]
I think this is a TensorFlow js issue, try updating maybe and file an issue on the tfjs repo if the error persists

**Comment by allrightzhu** [comment]
ok ,I will try this.
